services:
  main-database:
    container_name: stellar-db
    image: postgres:18.3
    restart: no
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      # gotta append _FILE to make it work by reading the file itself
      POSTGRES_PASSWORD_FILE: /run/secrets/db-root-pw
      POSTGRES_USER: mikalaras
      POSTGRES_DB: stellar-db
    secrets:
      - db-root-pw
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
  main-rabbitmq:
    container_name: stellar-rmq
    restart: no
    image: rabbitmq:4.3.0
    # set shared memory limit when using docker compose
    shm_size: 128mb
    #hostname: main-rabbit
    ports:
      - 5672:5672
    volumes:
      - rmq-data:/var/lib/rabbitmq
      - rmq-config:/etc/rabbitmq

  backofficer:
    build:
      context: ./backofficer
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: stellar-backofficer
    restart: no
    shm_size: 128mb
    ports:
      - 8100:8100
    depends_on:
      - main-database

  matching-engine:
    build:
      context: ./matching-engine
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: stellar-engine
    restart: no
    shm_size: 128mb
#    ports:
#      - 8200:8200
    depends_on:
      - main-database
      - main-rabbitmq

  order-gateway:
    build:
      context: ./order-gateway
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: stellar-gateway
    restart: no
    shm_size: 128mb
#    ports:
#      - 8300:8300
    depends_on:
      - main-database
      - main-rabbitmq

volumes:
  db-data:
    name: stellar-db-data
  rmq-data:
    name: stellar-rmq-data
  rmq-config:
    name: stellar-rmq-config

secrets:
  db-root-pw:
    file: ./database/dbrootpw.txt