name: Pull Request Health Checks
  
on: 
  pull_request:
    branches:
      - master

jobs:
 docker-compose-healthcheck:
   name: Docker Compose Healthcheck
   runs-on: ubuntu-24.04
   steps:
     - uses: actions/checkout@v6.0.2
     - uses: hoverkraft-tech/compose-action@v2.6.0
       with: 
         compose-file: ./compose.yaml
     - run: docker inspect stellar-rmq | grep Status
 
