name: PR Health Checks
  
on: 
  pull_request:
    branches:
      - master

jobs:
 docker-compose-healthcheck:
   name: Docker Deployment Check
   runs-on: ubuntu-latest
   steps:
     # bring in the code
     - uses: actions/checkout@v6.0.2
     # create the password files
     - run: |
         echo "asdgbtrh#%^3435" > ./database/dbrootpw.txt
         echo "sdag4353g25tg5!" > ./rabbitmq/adminpw.txt
       name: Password generation
     # package Quarkus apps
     - uses: actions/setup-java@v4
       with:
         java-version: '25.0.3'
         distribution: 'temurin'
         cache: maven
     # package with less logging and a snapshot update on the first run
     - run: |
         mvn package --batch-mode --update-snapshots -f ./backofficer -Dmaven.test.skip
         mvn package --batch-mode -f ./matching-engine -Dmaven.test.skip
         mvn package --batch-mode -f ./order-gateway -Dmaven.test.skip
       name: Quarkus app packaging
     # docker compose and health check
     - uses: hoverkraft-tech/compose-action@v2.6.0
       with: 
         compose-file: ./compose.yaml
     - run: |
         docker inspect stellar-rmq | grep -q "\"Status\": \"running\""
       name: RabbitMQ is up
     - run: | 
         docker inspect stellar-db | grep -q "\"Status\": \"running\""
       name: Database is up
 
